<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Opening balances (Phase 3.5.1, docs/acceptance-phase3.md section 6): a confirmed
 * invoice with no items that carries a customer's debt from before the system.
 *
 * opening_balance_customer_id is generated by the database (never written by the app):
 * the customer id while the sale is an opening balance and not void, otherwise NULL. Its
 * unique index allows one live opening balance per customer; voiding one releases it.
 * Same pattern as payments.reference_key.
 */
return new class extends Migration
{
    public function up(): void
    {
        $mysql = in_array(DB::getDriverName(), ['mysql', 'mariadb'], true);

        Schema::table('sales', function (Blueprint $table) {
            $table->boolean('is_opening_balance')->default(false)->after('source');
        });

        $expression = $mysql
            ? "case when `is_opening_balance` = 1 and `status` <> 'void' then `customer_id` end"
            : "case when is_opening_balance = 1 and status <> 'void' then customer_id end";

        Schema::table('sales', function (Blueprint $table) use ($mysql, $expression) {
            $column = $table->unsignedBigInteger('opening_balance_customer_id')->nullable();
            // MySQL: stored, so the unique index is on real data. SQLite can only ALTER-add virtual ones.
            $mysql ? $column->storedAs($expression) : $column->virtualAs($expression);

            $table->unique('opening_balance_customer_id');
        });
    }

    public function down(): void
    {
        Schema::table('sales', function (Blueprint $table) {
            $table->dropUnique(['opening_balance_customer_id']);
            $table->dropColumn('opening_balance_customer_id');
        });
        Schema::table('sales', function (Blueprint $table) {
            $table->dropColumn('is_opening_balance');
        });
    }
};
