<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * One real transaction, one valid payment: a MoMo transaction id, bank reference or
 * cheque number may appear on at most one *valid* payment per method.
 *
 * reference_key is generated by the database (never written by the app):
 *   METHOD:REFERENCE (upper-cased, spaces removed) when status = valid, method <> cash
 *   and a reference is present; otherwise NULL.
 * The unique index ignores NULLs, so cash and void payments never collide, and voiding a
 * payment releases its reference. Two simultaneous requests cannot both pass: the second
 * insert fails on the index (mapped to 409 duplicate_reference).
 */
return new class extends Migration
{
    public function up(): void
    {
        $mysql = in_array(DB::getDriverName(), ['mysql', 'mariadb'], true);

        $expression = $mysql
            ? "case when `status` = 'valid' and `method` <> 'cash' and `reference` is not null and trim(`reference`) <> ''
                then concat(`method`, ':', upper(replace(`reference`, ' ', ''))) end"
            : "case when status = 'valid' and method <> 'cash' and reference is not null and trim(reference) <> ''
                then method || ':' || upper(replace(reference, ' ', '')) end";

        Schema::table('payments', function (Blueprint $table) use ($mysql, $expression) {
            $column = $table->string('reference_key', 140)->nullable();

            // MySQL: stored, so the unique index is on real data. SQLite can only ALTER-add virtual ones.
            $mysql ? $column->storedAs($expression) : $column->virtualAs($expression);

            $table->unique('reference_key');
        });
    }

    public function down(): void
    {
        Schema::table('payments', function (Blueprint $table) {
            $table->dropUnique(['reference_key']);
            $table->dropColumn('reference_key');
        });
    }
};
